-- sprint4_password_reset.sql
USE consultorio_padre_pio;

CREATE TABLE IF NOT EXISTS TOKEN_RECUPERACION_USUARIO (
    token_id INT AUTO_INCREMENT,
    usuario_id INT NOT NULL,
    token VARCHAR(255) NOT NULL,
    fecha_creacion DATETIME DEFAULT CURRENT_TIMESTAMP,
    fecha_expira DATETIME NOT NULL,
    usado BOOLEAN DEFAULT FALSE,
    fecha_usado DATETIME NULL,
    CONSTRAINT PK_TOKEN_REC_USUARIO PRIMARY KEY (token_id),
    CONSTRAINT FK_TOKEN_REC_USUARIO FOREIGN KEY (usuario_id) REFERENCES USUARIO(usuario_id),
    CONSTRAINT UK_TOKEN_REC_USUARIO UNIQUE (token)
);

CREATE TABLE IF NOT EXISTS TOKEN_RECUPERACION_PACIENTE (
    token_id INT AUTO_INCREMENT,
    paciente_id INT NOT NULL,
    token VARCHAR(255) NOT NULL,
    fecha_creacion DATETIME DEFAULT CURRENT_TIMESTAMP,
    fecha_expira DATETIME NOT NULL,
    usado BOOLEAN DEFAULT FALSE,
    fecha_usado DATETIME NULL,
    CONSTRAINT PK_TOKEN_REC_PACIENTE PRIMARY KEY (token_id),
    CONSTRAINT FK_TOKEN_REC_PACIENTE FOREIGN KEY (paciente_id) REFERENCES PACIENTE(paciente_id),
    CONSTRAINT UK_TOKEN_REC_PACIENTE UNIQUE (token)
);
